// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"BootConsole","status":true,"description":"コンソールオート起動用プラグイン","parameters":{"consoleAutoBoot":"1","consolePosition":"100, 50"}},
{"name":"autoNewGame","status":true,"description":"起動時に自動ではじめからゲームを開始します。\r\nWeb用ミニゲームなど、タイトル画面が不要な場合などにどうぞ。","parameters":{"autoNewGame":"1","firstLimited":"1","allwaysOnTop":"0","autoDevTool":"1","autoContinueCommand":"自動コンティニュー","blockKey":"control"}},
{"name":"Scene_HomeBase","status":true,"description":"","parameters":{}}
];
