// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WTG_BootConsole","status":true,"description":"コンソールオート起動用プラグイン","parameters":{"consoleAutoBoot":"1","consolePosition":"100, 50"}}
];
