// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"WTG_BootConsole","status":true,"description":"コンソールオート起動用プラグイン","parameters":{"consoleAutoBoot":"1","consolePosition":"100, 50"}},
{"name":"WTG_Const","status":true,"description":"","parameters":{}},
{"name":"WTG_Scene_HomeBase","status":true,"description":"","parameters":{}},
{"name":"WTG_Scene_Map_Custom","status":true,"description":"","parameters":{}},
{"name":"WTG_Window_HomeCommand","status":true,"description":"","parameters":{}},
{"name":"WTG_Window_MapStat","status":true,"description":"","parameters":{}},
{"name":"WTG_Scene_Home","status":true,"description":"","parameters":{}},
{"name":"WTG_Scene_Inn","status":true,"description":"","parameters":{}},
{"name":"WTG_Window_InnCommand","status":true,"description":"","parameters":{}},
{"name":"WTG_Debug","status":true,"description":"","parameters":{}}
];
